content:
  - name: posts
    label: "文章"
    type: collection
    path: content/posts
    # 是否支持子文件夹
    subfolders: true
    # 文件命名规则
    filename: "{title}.md"
    # 字段列表
    fields:
      - { name: title, label: "标题", type: string, required: true }
      - { name: description, label: "描述", type: text, required: false }
      - { name: date, label: "发布日期", type: date }
      - { name: updated, label: "更新日期", type: date, required: false }
      - { name: image, label: "封面", type: string, required: false }
      - { name: categories, label: "分类", type: string, list: true, required: false }
      - { name: tags, label: "标签", type: string, list: true, required: false }
      - { name: type, label: "文章类型", type: select, options: { values: {name: "tech", label: "技术" }, { name: "story", label: "生活" }, { name: "memo", label: "碎碎念"}}, required: false }
      - { name: permalink, label: "永久链接", type: string, required: true, default: "/posts/" }
      - { name: uuid, label: "UUID", type: uuid, options: {editable: true, generate: true}}
      - { name: recommend, label: "精选文章", type: number, required: false, default: 0 }
      - { name: body, label: Body, type: rich-text, required: true }

  - name: friends
    label: "友链"
    type: file
    path: app/feeds.ts
    format: code

  - name: friends-tip
    label: "申请友链"
    type: file
    path: content/link.md
    format: code

  - name: blog-config
    label: "站点设置-blog.config"
    type: file
    path: blog.config.ts
    format: code

  - name: app-config
    label: "站点设置-app.config"
    type: file
    path: app/app.config.ts
    format: code