import type { FeedGroup } from '../app/types/feed'
// 友链检测 CLI 需要使用显式导入和相对路径
/**
	import { myFeed } from '../blog.config'
	eslint-disable-next-line unused-imports/no-unused-imports
	import { getFavicon, getGithubAvatar, getGithubIcon, getOciqGroupAvatar, getOicqAvatar, OicqAvatarSize } from './utils/img'
 */
export default [
	{
		name: '向开发者致敬',
		desc: 'Clarity 博客主题开发者。',
		// @keep-sorted { "keys": ["date"] }
		entries: [
			{
				author: '纸鹿本鹿',
				sitenick: '纸鹿摸鱼处',
				title: '纸鹿摸鱼处',
				desc: '纸鹿至麓不知路，支炉制露不止漉',
				link: 'https://blog.zhilu.site/',
				feed: 'https://blog.zhilu.site/atom.xml',
				icon: 'https://www.zhilu.site/api/avatar.png',
				avatar: 'https://www.zhilu.site/api/avatar.png',
				archs: ['Nuxt', 'Vercel'],
				date: '2023-12-23',
				comment: '主题开发者',
			},
		],
	},
	// #endregion
	// #region 网上邻居 since 2024
	{
		name: '网上邻居',
		desc: '哔——啵——电波通讯中，欢迎常来串门。',
		// @keep-sorted { "keys": ["date"] },
		entries: [
			{
				author: '张洪Heo',
				desc: '分享设计与科技生活',
				link: 'https://blog.zhheo.com/',
				feed: 'https://blog.zhheo.com/atom.xml',
				icon: 'https://blog.zhheo.com/img/favicon4.0.webp',
				avatar: 'https://blog.zhheo.com/img/favicon4.0.webp',
				archs: ['Hexo', 'EdgeOne'],
				date: '2024-02-02',
				comment: '知名博主，其博客设计风格被众多人借鉴。',
			},
			{
				author: 'Moliam',
				desc: 'Linux/Python/C',
				link: 'https://www.moliam.space/',
				icon: 'https://www.moliam.space/img/avatar.png',
				avatar: 'https://www.moliam.space/img/avatar.png',
				archs: ['Hexo', '虚拟主机'],
				date: '2024-02-02',
				comment: 'Fluid社群好友，Linux爱好者，Python和C语言开发者。',
			},
			{
				author: 'GISHAI',
				desc: '真正的伟大,即在于以脆弱的凡人之躯而具有神性的不可战胜。',
				link: 'https://gishai.top/blog/',
				icon: 'https://gishai.top/media/icons/favicon.png',
				avatar: 'https://gishai.top/media/icons/favicon.png',
				archs: ['Hexo', '虚拟主机'],
				date: '2024-02-02',
				comment: 'Fluid社群好友。',
			},
			{
				author: 'Oyiso\'s Blog',
				desc: 'The shortest answer is doing',
				link: 'https://oyiso.cn',
				icon: 'https://oyiso.cn/logo.png',
				avatar: 'https://oyiso.cn/logo.png',
				archs: ['WordPress', 'EdgeOne'],
				date: '2024-02-02',
				comment: 'WordPress主题开发者，前端爱好者。',
			},
			{
				author: 'AimTao',
				desc: '来日做春风，浪漫且自由',
				link: 'https://www.aimtao.net/',
				feed: 'https://www.aimtao.net/atom.xml',
				icon: 'https://file.dhbxs.top/2025/10/gedefhgl.webp',
				avatar: 'https://file.dhbxs.top/2025/10/gedefhgl.webp',
				archs: ['Hexo', '虚拟主机'],
				date: '2024-02-02',
				comment: 'Fluid社群好友，小米员工，Android系统开发工程师',
			},
			{
				author: '会飞的猫',
				desc: '记录时间带走的东西',
				link: 'https://blog.flycat.tech',
				feed: 'https://blog.flycat.tech/rss.xml',
				icon: 'https://img-gh.flycat.tech/10/main/avatar.jpg',
				avatar: 'https://img-gh.flycat.tech/10/main/avatar.jpg',
				archs: ['Halo', '虚拟主机'],
				date: '2024-02-02',
				comment: 'Java开发攻城狮',
			},
			{
				author: '唯知笔记',
				desc: '在这里，我们分享最新的技术趋势、编程技巧和开发心得，一起成长，共同进步',
				link: 'https://note.weizwz.com',
				feed: 'https://note.weizwz.com/feed.xml',
				icon: 'https://p.weizwz.com/logo_a4353391cbf0889b.webp',
				avatar: 'https://p.weizwz.com/logo_a4353391cbf0889b.webp',
				archs: ['VitePress', 'Cloudflare'],
				date: '2024-02-02',
				comment: '前端开发攻城狮，技术博主',
			},
			{
				author: 'iren • Moment Collector',
				desc: '一名在读的运维工程师，记录那些我在人间生活的日子。',
				link: 'https://blog.mletter.cn/',
				feed: 'https://blog.mletter.cn/rss.xml',
				icon: 'https://file.dhbxs.top/blog_link_favicon/1776244548759_74954127.webp',
				avatar: 'https://file.dhbxs.top/blog_link_favicon/1776244548759_74954127.webp',
				archs: ['Astro', 'EdgeOne'],
				date: '2024-02-02',
				comment: '运维工程师',
			},
			{
				author: 'YYsuni',
				desc: 'YYsuni 的个人博客，记录前端开发、探索笔记。前端 UI 更新代码仓库。',
				link: 'https://www.yysuni.com/',
				feed: 'https://www.yysuni.com/rss.xml',
				icon: 'https://www.yysuni.com/favicon.png',
				avatar: 'https://www.yysuni.com/favicon.png',
				archs: ['Cloudflare'],
				date: '2024-02-02',
				comment: '前端开发工程师，博客为自主开发',
			},
			{
				author: 'Honesty',
				desc: '从浩瀚无垠的知识中看到一缕光',
				link: 'https://blog.hehouhui.cn',
				icon: 'https://www.hehouhui.cn/images/avatar.jpeg',
				avatar: 'https://www.hehouhui.cn/images/avatar.jpeg',
				archs: ['NotionNext', 'Vercel'],
				date: '2024-02-02',
				comment: '前端开发工程师，博客为自主开发',
			},
			{
				author: 'HaoUp’s Blog',
				desc: '学习网络知识、积累兴趣的地方。',
				link: 'https://blog.528688.cn',
				icon: 'https://cdn.528688.cn/favicon.ico',
				avatar: 'https://cdn.528688.cn/favicon.ico',
				archs: ['Halo', '虚拟主机'],
				date: '2026-05-01',
				comment: '前端工程师，博客主题很亮眼',
			},
		],
	},
	// #endregion
] satisfies FeedGroup[]
